export const experience = [
  {
    title: "Lead FrontEnd Architect",
    titleEn: "Lead FrontEnd Architect",
    company: "ONPE - Oficina Nacional de Procesos Electorales",
    period: "Mayo 2023 - Presente",
    periodEn: "May 2023 - Present",
    description:
      "Liderazgo en desarrollo frontend de sistemas electorales de impacto nacional con React, Next.js y TypeScript",
    descriptionEn:
      "Frontend development leadership for national impact electoral systems with React, Next.js and TypeScript",
    achievements: [
      "Lideré la estructuración inicial y desarrollo de múltiples proyectos frontend institucionales",
      "Reducción de tiempos de desarrollo en 30% mediante estandarización de componentes y patrones",
      "Disminución de errores en 25% con manejo global Axios y validaciones robustas",
      "Migración de Next.js a Vite para mejor control de despliegue estático en AWS S3",
      "Diseño de soluciones escalables optimizando accesibilidad y rendimiento",
      "Coordinación con backend y QA para asegurar calidad en cada entrega",
      "Documentación de buenas prácticas y propuesta de mejoras continuas",
    ],
    achievementsEn: [
      "Led initial structuring and development of multiple institutional frontend projects",
      "30% development time reduction through component and pattern standardization",
      "25% error reduction with global Axios handling and robust validations",
      "Next.js to Vite migration for better static deployment control on AWS S3",
      "Design of scalable solutions optimizing accessibility and performance",
      "Coordination with backend and QA to ensure quality in each delivery",
      "Documentation of best practices and proposal of continuous improvements",
    ],
    current: true,
  },
  {
    title: "Full Stack Developer",
    titleEn: "Full Stack Developer",
    company: "Periferia IT Group – (cliente: UTP)",
    period: "Abril 2025 – Julio 2025",
    periodEn: "April 2025 – July 2025",
    description:
      "Desarrollo completo de 2 proyectos académicos: Melbo (desde cero) y mejora de Mel Web (sistema existente) con React, Next.js y NestJS",
    descriptionEn:
      "Complete development of 2 academic projects: Melbo (from scratch) and Mel Web improvement (existing system) with React, Next.js and NestJS",
    achievements: [
      "Desarrollo frontend completo del proyecto Melbo desde cero",
      "Mejora y optimización del sistema Mel Web existente",
      "Reducción de tiempo de carga inicial en 1.5 segundos mediante optimización",
      "Implementación de Screaming Architecture para mejor organización del código",
      "Refactorización de componentes complejos y optimización de hooks",
      "Apoyo en backend con NestJS y PostgreSQL, ajustando integraciones post-migración",
      "Contribución a decisiones técnicas clave que optimizaron recursos y tiempos",
    ],
    achievementsEn: [
      "Complete frontend development of Melbo project from scratch",
      "Improvement and optimization of existing Mel Web system",
      "1.5 second initial loading time reduction through optimization",
      "Screaming Architecture implementation for better code organization",
      "Refactoring of complex components and hook optimization",
      "Backend support with NestJS and PostgreSQL, adjusting post-migration integrations",
      "Contribution to key technical decisions that optimized resources and development time",
    ],
    current: false,
  },
  {
    title: "Full Stack Developer (Freelancer)",
    titleEn: "Full Stack Developer (Freelancer)",
    company: "Analytia Consulting",
    period: "Septiembre 2023 - Presente",
    periodEn: "September 2023 - Present",
    description: "Desarrollo full stack con React, Node.js y servicios AWS",
    descriptionEn:
      "Full stack development with React, Node.js and AWS services",
    achievements: [
      "Reducción de tiempos de entrega en 35%",
      "Mejora de eficiencia operativa en 40%",
      "Desarrollo de soluciones móviles con Flutter",
      "Implementación de servicios AWS (EC2, Lambda, S3)",
    ],
    achievementsEn: [
      "35% delivery time reduction",
      "40% operational efficiency improvement",
      "Mobile solution development with Flutter",
      "AWS services implementation (EC2, Lambda, S3)",
    ],
    current: true,
  },
  {
    title: "Front-End Developer",
    company: "Trust Consulting – (cliente: Auna Salud)",
    period: "Septiembre 2023 - Diciembre 2023",
    periodEn: "September 2023 - December 2023",
    description: "Desarrollo de e-commerce y optimización de conversiones",
    descriptionEn: "E-commerce development and conversion optimization",
    achievements: [
      "Incremento de eficiencia de compra en 10%",
      "Aumento de tasa de apertura de emails en 15%",
      "Incremento de conversión en 10%",
      "Optimización de plataforma de pago",
    ],
    achievementsEn: [
      "10% purchase efficiency increase",
      "15% email open rate increase",
      "10% conversion increase",
      "Payment platform optimization",
    ],
    current: false,
  },
  {
    title: "Desarrollador Web",
    titleEn: "Web Developer",
    company: "GLR - Grupo La República Publicaciones",
    period: "Octubre 2022 - Septiembre 2023",
    periodEn: "October 2022 - September 2023",
    description: "Desarrollo de plataformas web con React y Next.js",
    descriptionEn: "Web platform development with React and Next.js",
    achievements: [
      "Mejora de velocidad de carga en 40%",
      "Aumento de tráfico orgánico en 20%",
      "Desarrollo de 2 plataformas completas (Kbeat y Spoiler)",
      "Implementación de SSR y optimización SEO",
    ],
    achievementsEn: [
      "40% loading speed improvement",
      "20% organic traffic increase",
      "Development of 2 complete platforms (Kbeat and Spoiler)",
      "SSR implementation and SEO optimization",
    ],
    current: false,
  },
  {
    title: "Front-End Developer",
    company: "Softaki - Softaki Software Solutions",
    period: "Enero 2022 - Diciembre 2022",
    periodEn: "January 2022 - December 2022",
    description: "Desarrollo de aplicaciones web y móviles con React",
    descriptionEn: "Web and mobile application development with React",
    achievements: [
      "Incremento de tráfico orgánico en 20%",
      "Integración con pasarelas de pago (Mercado Pago)",
      "Implementación de autenticación segura con JWT",
      "Desarrollo de aplicaciones móviles",
    ],
    achievementsEn: [
      "20% organic traffic increase",
      "Payment gateway integration (Mercado Pago)",
      "Secure authentication implementation with JWT",
      "Mobile application development",
    ],
    current: false,
  },
];
