export const projects = [
  {
    id: 1,
    title: "Voto Digital - Sistema Electoral Nacional",
    titleEn: "Digital Voting - National Electoral System",
    company: "ONPE",
    description:
      "Sistema integral de voto electrónico para las próximas elecciones nacionales del país, con múltiples módulos interconectados.",
    descriptionEn:
      "Comprehensive electronic voting system for the upcoming national elections, with multiple interconnected modules.",
    longDescription:
      "Lideré el desarrollo frontend completo del Sistema de Voto Digital que será utilizado en las próximas elecciones nacionales del país. Este proyecto de alto impacto nacional consiste en múltiples módulos interconectados: Módulo de Administración, Módulo de Votación, Módulo de Verificación, y la plataforma web principal de ONPE ID para validación de identidad electrónica con lectora biométrica y aplicación móvil. Establecí la arquitectura frontend desde cero, implementando mejores prácticas y patrones de diseño. El sistema incluye gestión de estado con Zustand, visualización de datos complejos con React Table, manejo eficiente de datos con React Query, formularios optimizados con React Hook Form y validación con Zod, todo construido con Vite, Next.js, TypeScript y TailwindCSS.",
    longDescriptionEn:
      "Led the complete frontend development of the Digital Voting System that will be used in the upcoming national elections. This high-impact national project consists of multiple interconnected modules: Administration Module, Voting Module, Verification Module, and the main ONPE ID web platform for electronic identity validation with biometric reader and mobile application. Established the frontend architecture from scratch, implementing best practices and design patterns. The system includes state management with Zustand, complex data visualization with React Table, efficient data handling with React Query, optimized forms with React Hook Form and validation with Zod, all built with Vite, Next.js, TypeScript and TailwindCSS.",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Zustand",
      "React Query",
      "React Table",
      "React Hook Form",
      "Zod",
      "TailwindCSS",
      "Vite",
    ],
    achievements: [
      "Sistema electoral de impacto nacional para próximas elecciones",
      "Liderazgo frontend en 4 módulos interconectados",
      "Arquitectura frontend establecida desde cero",
      "Integración con lectora biométrica y app móvil",
      "Componentes reutilizables y escalables",
      "Interfaces 100% responsivas y accesibles",
    ],
    achievementsEn: [
      "National impact electoral system for upcoming elections",
      "Frontend leadership across 4 interconnected modules",
      "Frontend architecture established from scratch",
      "Biometric reader and mobile app integration",
      "Reusable and scalable components",
      "100% responsive and accessible interfaces",
    ],
    category: "Frontend",
    year: "2023-2024",
    featured: true,
    images: [
      "/projects/voto/voto1.png",
      "/projects/voto/voto2.png",
      "/projects/voto/voto3.png",
      "/projects/voto/voto4.png",
      "/projects/voto/voto5.png",
      "/projects/voto/voto6.png",
      "/projects/voto/voto7.png",
      "/projects/voto/voto8.png",
      "/projects/voto/voto9.png",
      "/projects/voto/voto10.png",
      "/projects/voto/voto11.png",
      "/projects/voto/voto12.png",
      "/projects/voto/voto13.png",
      "/projects/voto/voto14.png",
    ],
  },
  {
    id: 2,
    title: "SAER - Dashboard Administrativo",
    titleEn: "SAER - Administrative Dashboard",
    company: "ONPE",
    description:
      "Dashboard administrativo con gestión de documentos, validaciones y visualización de archivos multimedia.",
    descriptionEn:
      "Administrative dashboard with document management, validations and multimedia file visualization.",
    longDescription:
      "Me encargué de rescatar y mejorar significativamente este proyecto que tenía múltiples fallencias y funcionalidades incompletas cuando asumí el liderazgo. Aunque no inicié el proyecto desde cero, fui clave para sacarlo adelante resolviendo bugs críticos y implementando mejoras sustanciales. El sistema es un dashboard administrativo completo donde se pueden subir y gestionar documentos con validaciones robustas, incluyendo archivos Excel, PDF, videos, imágenes y otros formatos multimedia. Implementé funcionalidades de visualización de PDF, reproducción de videos y galería de fotos. El proyecto utiliza Angular con TypeScript, aprovechando las capacidades nativas del framework como Standalone Components, y se comunica con APIs externas para la gestión de datos. A pesar de que Angular tiene muchas funcionalidades integradas en su framework, implementé librerías adicionales cuando fue necesario para optimizar la experiencia de usuario y la funcionalidad del sistema.",
    longDescriptionEn:
      "Took charge of rescuing and significantly improving this project that had multiple shortcomings and incomplete functionalities when I assumed leadership. Although I didn't start the project from scratch, I was key to bringing it forward by resolving critical bugs and implementing substantial improvements. The system is a complete administrative dashboard where documents can be uploaded and managed with robust validations, including Excel files, PDFs, videos, images and other multimedia formats. Implemented PDF visualization features, video playback and photo gallery. The project uses Angular with TypeScript, leveraging the framework's native capabilities such as Standalone Components, and communicates with external APIs for data management. Despite Angular having many integrated functionalities in its framework, I implemented additional libraries when necessary to optimize user experience and system functionality.",
    technologies: [
      "Angular",
      "TypeScript",
      "CSS",
      "Standalone Components",
      "Angular Material",
      "RxJS",
      "Angular Forms",
      "Angular Router",
    ],
    achievements: [
      "Rescate y mejora significativa de proyecto con múltiples fallencias",
      "Resolución de bugs críticos que permitieron sacar el proyecto adelante",
      "Implementación de dashboard administrativo completo con gestión de documentos",
      "Sistema de validaciones robustas para subida de archivos (Excel, PDF, videos, imágenes)",
      "Funcionalidades de visualización de PDF y reproducción de videos",
      "Galería de fotos y gestión multimedia completa",
      "Comunicación eficiente con APIs externas",
      "Optimización de experiencia de usuario con librerías especializadas",
    ],
    achievementsEn: [
      "Rescue and significant improvement of project with multiple shortcomings",
      "Resolution of critical bugs that allowed the project to move forward",
      "Implementation of complete administrative dashboard with document management",
      "Robust validation system for file uploads (Excel, PDF, videos, images)",
      "PDF visualization and video playback features",
      "Photo gallery and complete multimedia management",
      "Efficient communication with external APIs",
      "User experience optimization with specialized libraries",
    ],
    category: "Frontend",
    year: "2023-2024",
    featured: true,
    images: [
      "/projects/saer/saer1.png",
      "/projects/saer/saer2.png",
      "/projects/saer/saer3.png",
      "/projects/saer/saer4.png",
      "/projects/saer/saer5.png",
      "/projects/saer/saer6.png",
      "/projects/saer/saer7.png",
      "/projects/saer/saer8.png",
      "/projects/saer/saer9.png",
      "/projects/saer/saer10.png",
      "/projects/saer/saer11.png",
      "/projects/saer/saer12.png",
      "/projects/saer/saer13.png",
    ],
  },
  {
    id: 3,
    title: "VENP - Voto Electrónico No Presencial",
    titleEn: "VENP - Non-Presential Electronic Voting",
    company: "ONPE",
    description:
      "Sistema de voto electrónico no presencial exitosamente implementado en las elecciones del Colegio de Ingenieros del Perú, con múltiples módulos interconectados.",
    descriptionEn:
      "Non-presential electronic voting system successfully implemented in the Peruvian Engineers College elections, with multiple interconnected modules.",
    longDescription:
      "Lideré el desarrollo frontend completo del sistema VENP que ya ha sido exitosamente utilizado en múltiples ocasiones para las elecciones del Colegio de Ingenieros del Perú, garantizando un voto seguro y confiable. Este proyecto de alto impacto consiste en múltiples módulos interconectados: Módulo de Votación, Módulo de Soporte, la plataforma web principal de ONPE ID para autenticación con lectora biométrica y aplicación móvil, y el Módulo Administrativo. Establecí la arquitectura frontend desde cero, implementando mejores prácticas y patrones de diseño. El sistema incluye gestión de estado con Zustand, visualización de datos complejos con React Table, manejo eficiente de datos con React Query, formularios optimizados con React Hook Form y validación con Zod, todo construido con Vite, Next.js, TypeScript y TailwindCSS.",
    longDescriptionEn:
      "Led the complete frontend development of the VENP system that has been successfully used on multiple occasions for the Peruvian Engineers College elections, ensuring secure and reliable voting. This high-impact project consists of multiple interconnected modules: Voting Module, Support Module, the main ONPE ID web platform for authentication with biometric reader and mobile application, and the Administrative Module. Established the frontend architecture from scratch, implementing best practices and design patterns. The system includes state management with Zustand, complex data visualization with React Table, efficient data handling with React Query, optimized forms with React Hook Form and validation with Zod, all built with Vite, Next.js, TypeScript and TailwindCSS.",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Zustand",
      "React Query",
      "React Table",
      "React Hook Form",
      "Zod",
      "TailwindCSS",
      "Vite",
    ],
    achievements: [
      "Sistema electoral exitosamente implementado en elecciones del Colegio de Ingenieros",
      "Liderazgo frontend en 4 módulos interconectados",
      "Arquitectura frontend establecida desde cero",
      "Integración con lectora biométrica y app móvil",
      "Voto seguro y confiable garantizado",
      "Interfaces 100% responsivas y accesibles",
    ],
    achievementsEn: [
      "Electoral system successfully implemented in Engineers College elections",
      "Frontend leadership across 4 interconnected modules",
      "Frontend architecture established from scratch",
      "Biometric reader and mobile app integration",
      "Secure and reliable voting guaranteed",
      "100% responsive and accessible interfaces",
    ],
    category: "Frontend",
    year: "2023-2024",
    featured: true,
    images: [
      "/projects/venp/venp1.png",
      "/projects/venp/venp2.png",
      "/projects/venp/venp3.png",
      "/projects/venp/venp4.png",
      "/projects/venp/venp5.png",
      "/projects/venp/venp6.png",
      "/projects/venp/venp7.png",
      "/projects/venp/venp8.png",
      "/projects/venp/venp9.png",
      "/projects/venp/venp10.png",
      "/projects/venp/venp11.png",
      "/projects/venp/venp12.png",
      "/projects/venp/venp13.png",
      "/projects/venp/venp14.png",
    ],
  },
  {
    id: 4,
    title: "Mel Web - Sistema Académico UTP",
    titleEn: "Mel Web - UTP Academic System",
    company: "Periferia IT Group - UTP",
    description:
      "Sistema académico completo con 2 proyectos interconectados: sistema de matrículas y módulo administrativo con logs de APIs.",
    descriptionEn:
      "Complete academic system with 2 interconnected projects: enrollment system and administrative module with API logs.",
    longDescription:
      "Lideré el desarrollo frontend completo de dos proyectos interconectados para la Universidad Tecnológica del Perú (UTP). Como único desarrollador frontend a cargo, tomé decisiones clave en arquitectura y diseño. El primer proyecto consistía en el sistema de matrículas de la UTP, donde agregué guías interactivas y nuevas funcionalidades. El segundo proyecto era una extensión del primero: un módulo administrativo para monitorear logs de APIs, visualizar tiempos de respuesta, tipos de errores y métricas de rendimiento. Implementé React Hook Form con Zod para validaciones robustas, React Table para visualización de datos complejos, y paginación a nivel backend y frontend. También apoyé en tareas de backend con PostgreSQL, NestJS y Node.js, escribiendo sentencias SQL complejas. Reduje el tiempo de carga inicial en 1.5 segundos mediante optimización de componentes y lógica de hooks.",
    longDescriptionEn:
      "Led the complete frontend development of two interconnected projects for the Technological University of Peru (UTP). As the only frontend developer in charge, I made key decisions in architecture and design. The first project consisted of the UTP enrollment system, where I added interactive guides and new features. The second project was an extension of the first: an administrative module to monitor API logs, visualize response times, error types and performance metrics. Implemented React Hook Form with Zod for robust validations, React Table for complex data visualization, and pagination at both backend and frontend levels. Also supported backend tasks with PostgreSQL, NestJS and Node.js, writing complex SQL statements. Reduced initial loading time by 1.5 seconds through component optimization and hook logic.",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Zustand",
      "React Query",
      "React Table",
      "React Hook Form",
      "Zod",
      "Vite",
      "PostgreSQL",
      "NestJS",
      "Node.js",
    ],
    achievements: [
      "Liderazgo frontend único en 2 proyectos interconectados",
      "Reducción de tiempo de carga inicial en 1.5 segundos",
      "Sistema de matrículas con guías interactivas",
      "Módulo administrativo con monitoreo de APIs",
      "Apoyo en backend con PostgreSQL y NestJS",
      "Toma de decisiones clave en arquitectura",
    ],
    achievementsEn: [
      "Sole frontend leadership across 2 interconnected projects",
      "1.5 second initial loading time reduction",
      "Enrollment system with interactive guides",
      "Administrative module with API monitoring",
      "Backend support with PostgreSQL and NestJS",
      "Key decision making in architecture",
    ],
    category: "Full Stack",
    year: "2025",
    featured: true,
    images: [
      "/projects/utp/utp1.png",
      "/projects/utp/utp2.png",
      "/projects/utp/utp3.png",
      "/projects/utp/utp4.png",
      "/projects/utp/utp5.png",
      "/projects/utp/utp6.png",
      "/projects/utp/utp7.png",
      "/projects/utp/utp8.png",
      "/projects/utp/utp9.png",
      "/projects/utp/utp10.png",
      "/projects/utp/utp11.png",
      "/projects/utp/utp12.png",
    ],
  },
  {
    id: 5,
    title: "Rindo - Software as a Service (SaaS)",
    titleEn: "Rindo - Software as a Service (SaaS)",
    company: "Analytia Consulting",
    description:
      "Plataforma SaaS para gestión empresarial con roles, flujos de aprobación y reportes automatizados.",
    descriptionEn:
      "SaaS platform for business management with roles, approval workflows and automated reports.",
    longDescription:
      "Lideré el desarrollo completo de una plataforma SaaS empresarial que permite a las empresas gestionar gastos, reportes y flujos de aprobación. El sistema cuenta con roles diferenciados (rendidores, aprobadores, administradores) con permisos específicos por área empresarial. Implementé un flujo de aprobación donde los rendidores crean gastos que pasan por un proceso de validación con los aprobadores. El sistema incluye integración con AWS Lambda (Python) para procesamiento de imágenes OCR desde S3, generación de reportes en Excel con estadísticas y gráficos, y notificaciones en tiempo real con Web Sockets. Utilicé patrones Repository en el backend con NestJS, implementé las mejores prácticas de seguridad y escalabilidad, y desarrollé tanto el frontend con React, Vite, TypeScript y TailwindCSS como el backend completo.",
    longDescriptionEn:
      "Led the complete development of a business SaaS platform that allows companies to manage expenses, reports and approval workflows. The system features differentiated roles (expense reporters, approvers, administrators) with specific permissions by business area. Implemented an approval workflow where expense reporters create expenses that go through a validation process with approvers. The system includes AWS Lambda (Python) integration for OCR image processing from S3, Excel report generation with statistics and charts, and real-time notifications with Web Sockets. Used Repository patterns in the backend with NestJS, implemented security and scalability best practices, and developed both the frontend with React, Vite, TypeScript and TailwindCSS and the complete backend.",
    technologies: [
      "React",
      "Vite",
      "TypeScript",
      "TailwindCSS",
      "React Query",
      "React Table",
      "Axios",
      "Node.js",
      "MongoDB",
      "NestJS",
      "AWS Lambda",
      "AWS S3",
      "Zustand",
      "React Hook Form",
      "Zod",
      "Web Sockets",
      "TypeORM",
    ],
    achievements: [
      "Plataforma SaaS completa con roles y permisos diferenciados",
      "Sistema de flujos de aprobación automatizado",
      "Integración con AWS Lambda para procesamiento OCR de imágenes",
      "Generación de reportes en Excel con estadísticas y gráficos",
      "Notificaciones en tiempo real con Web Sockets",
      "Implementación de patrones Repository y mejores prácticas",
      "Desarrollo full stack completo (frontend y backend)",
    ],
    achievementsEn: [
      "Complete SaaS platform with differentiated roles and permissions",
      "Automated approval workflow system",
      "AWS Lambda integration for OCR image processing",
      "Excel report generation with statistics and charts",
      "Real-time notifications with Web Sockets",
      "Repository patterns implementation and best practices",
      "Complete full stack development (frontend and backend)",
    ],
    category: "Full Stack",
    year: "2023-2024",
    featured: true,
    images: [
      "/projects/rindo/rindo1.png",
      "/projects/rindo/rindo2.png",
      "/projects/rindo/rindo3.png",
      "/projects/rindo/rindo4.png",
      "/projects/rindo/rindo5.png",
      "/projects/rindo/rindo6.png",
      "/projects/rindo/rindo7.png",
      "/projects/rindo/rindo8.png",
      "/projects/rindo/rindo9.png",
      "/projects/rindo/rindo10.png",
      "/projects/rindo/rindo11.png",
    ],
  },

  {
    id: 6,
    title: "Conformidad - Automatización de Facturas SaaS",
    titleEn: "Conformidad - Invoice Automation SaaS",
    company: "Analytia Consulting",
    description:
      "SaaS de automatización de facturas y comprobantes con integración SUNAT y notificaciones automáticas.",
    descriptionEn:
      "Invoice and receipt automation SaaS with SUNAT integration and automatic notifications.",
    longDescription:
      "Desarrollé en un 80% este proyecto SaaS de automatización de facturas y comprobantes que identifica automáticamente el estado de las facturas para determinar si pasan a factoring o están en estado de disconformidad. El sistema envía alertas automáticas cuando las facturas están disconformes y se conecta con SUNAT mediante una API oficial para extraer información de las facturas que están registradas en SUNAT, almacenando toda la información en MongoDB. El proyecto es full stack completo que desarrollé tanto en backend como frontend. En el frontend utilicé Vite, React, TypeScript, Zustand, React Table, React Hook Form y Zod. En el backend implementé Node.js, NestJS y MongoDB. Además, consumí un Lambda que me proporcionaron con Python y Node.js para dar conformidad o disconformidad automáticamente y enviar notificaciones por correo cuando las facturas cambian de estado. Las notificaciones de correo se implementaron usando servicios de correo con SendGrid y plantillas personalizadas creadas con HTML.",
    longDescriptionEn:
      "Developed 80% of this invoice and receipt automation SaaS project that automatically identifies invoice status to determine if they pass to factoring or are in non-compliance status. The system sends automatic alerts when invoices are non-compliant and connects with SUNAT through an official API to extract information from invoices registered in SUNAT, storing all information in MongoDB. The project is complete full stack that I developed in both backend and frontend. In the frontend I used Vite, React, TypeScript, Zustand, React Table, React Hook Form and Zod. In the backend I implemented Node.js, NestJS and MongoDB. Additionally, I consumed a Lambda that was provided to me with Python and Node.js to automatically give compliance or non-compliance and send email notifications when invoices change status. Email notifications were implemented using email services with SendGrid and custom templates created with HTML.",
    technologies: [
      "React",
      "Vite",
      "TypeScript",
      "Zustand",
      "React Query",
      "React Table",
      "React Hook Form",
      "Zod",
      "Node.js",
      "NestJS",
      "MongoDB",
      "Python",
      "AWS Lambda",
      "SendGrid",
      "SUNAT API",
      "HTML",
    ],
    achievements: [
      "Desarrollo del 80% del proyecto SaaS de automatización de facturas",
      "Sistema automático de identificación de estado de facturas para factoring",
      "Integración con API oficial de SUNAT para extracción de información",
      "Almacenamiento y gestión de datos de facturas en MongoDB",
      "Consumo de Lambda con Python y Node.js para automatización de conformidad/disconformidad",
      "Sistema de notificaciones automáticas por correo con SendGrid",
      "Plantillas personalizadas de correo creadas con HTML",
      "Desarrollo full stack completo (frontend y backend)",
    ],
    achievementsEn: [
      "Development of 80% of the invoice automation SaaS project",
      "Automatic invoice status identification system for factoring",
      "Integration with official SUNAT API for information extraction",
      "Invoice data storage and management in MongoDB",
      "Lambda consumption with Python and Node.js for compliance/non-compliance automation",
      "Automatic email notification system with SendGrid",
      "Custom email templates created with HTML",
      "Complete full stack development (frontend and backend)",
    ],
    category: "Full Stack",
    year: "2023-2024",
    featured: true,
    images: [
      "/projects/conformidad/conformidad1.png",
      "/projects/conformidad/conformidad2.png",
      "/projects/conformidad/conformidad3.png",
      "/projects/conformidad/conformidad4.png",
      "/projects/conformidad/conformidad5.png",
      "/projects/conformidad/conformidad6.png",
      "/projects/conformidad/conformidad7.png",
      "/projects/conformidad/conformidad8.png",
      "/projects/conformidad/conformidad9.png",
    ],
  },

  {
    id: 7,
    title: "La República - Plataforma de Noticias",
    titleEn: "La República - News Platform",
    company: "Grupo La República",
    description:
      "Desarrollo y mantenimiento de plataformas de noticias con SSR, SEO optimizado y componentes reutilizables.",
    descriptionEn:
      "Development and maintenance of news platforms with SSR, optimized SEO and reusable components.",
    longDescription:
      "Colaboré estrechamente con el equipo de backend para integrar APIs de manera eficiente, reduciendo los tiempos de respuesta de las funcionalidades en un 30%. Implementé server-side rendering (SSR) en diversas páginas, mejorando la velocidad de carga en un 40% y logrando un aumento del 20% en el tráfico orgánico gracias a la optimización del SEO. Contribuí al diseño y desarrollo de componentes reutilizables, acelerando el tiempo de desarrollo de nuevas funcionalidades en un 20% y simplificando el mantenimiento del código. También apoyé en el desarrollo y optimización del sistema de anuncios, fuente principal de ingresos del Grupo La República, implementando integraciones con GraphQL para mejorar el rendimiento de las consultas de datos. El proyecto incluye Libero, Wapa y El Popular, todas plataformas de noticias con integración de Google Analytics, meta tags Open Graph para SEO, y optimización de posicionamiento en buscadores.",
    longDescriptionEn:
      "Collaborated closely with the backend team to efficiently integrate APIs, reducing response times of functionalities by 30%. Implemented server-side rendering (SSR) on various pages, improving loading speed by 40% and achieving a 20% increase in organic traffic thanks to SEO optimization. Contributed to the design and development of reusable components, accelerating development time of new features by 20% and simplifying code maintenance. Also supported the development and optimization of the advertising system, the main revenue source of Grupo La República, implementing GraphQL integrations to improve data query performance. The project includes Libero, Wapa and El Popular, all news platforms with Google Analytics integration, Open Graph meta tags for SEO, and search engine positioning optimization.",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "GraphQL",
      "SSR",
      "SASS",
      "Google Analytics",
      "SEO",
    ],
    achievements: [
      "Reducción de tiempos de respuesta en 30% mediante integración eficiente de APIs",
      "Mejora de velocidad de carga en 40% con implementación de SSR",
      "Aumento de tráfico orgánico en 20% gracias a optimización SEO",
      "Aceleración del desarrollo en 20% con componentes reutilizables",
      "Integración de Google Analytics y meta tags Open Graph",
      "Desarrollo y optimización del sistema de anuncios (fuente principal de ingresos)",
      "Implementación de GraphQL para mejorar rendimiento de consultas de datos",
      "Mantenimiento y mejora de múltiples plataformas (Libero, Wapa, El Popular)",
    ],
    achievementsEn: [
      "30% response time reduction through efficient API integration",
      "40% loading speed improvement with SSR implementation",
      "20% organic traffic increase thanks to SEO optimization",
      "20% development acceleration with reusable components",
      "Google Analytics and Open Graph meta tags integration",
      "Development and optimization of advertising system (main revenue source)",
      "GraphQL implementation to improve data query performance",
      "Maintenance and improvement of multiple platforms (Libero, Wapa, El Popular)",
    ],
    category: "Frontend",
    year: "2022-2023",
    featured: true,
    liveUrl: "https://larepublica.pe",
    images: [
      "/projects/larepublica/larepublica1.png",
      "/projects/larepublica/larepublica2.png",
      "/projects/larepublica/larepublica3.png",
      "/projects/larepublica/larepublica4.png",
      "/projects/larepublica/larepublica5.png",
      "/projects/larepublica/larepublica6.png",
      "/projects/larepublica/larepublica7.png",
      "/projects/larepublica/larepublica8.png",
      "/projects/larepublica/larepublica9.png",
      "/projects/larepublica/larepublica10.png",
      "/projects/larepublica/larepublica11.png",
      "/projects/larepublica/larepublica12.png",
    ],
  },

  {
    id: 8,
    title: "Kbeat & Spoiler - Plataforma de noticias",
    titleEn: "Kbeat & Spoiler - News Platform",
    company: "Grupo La República",
    description:
      "Desarrollo desde cero de dos plataformas de noticias con diseños únicos y maquetación moderna.",
    descriptionEn:
      "Development from scratch of two news platforms with unique designs and modern layout.",
    longDescription:
      "Desarrollé desde cero, junto con un compañero, dos plataformas de noticias completamente nuevas: Kbeat y Spoiler. Aunque nos basamos en la estructura existente de La República, creamos ambos proyectos desde el inicio hasta el final, incluyendo nuevos diseños, maquetación completa y funcionalidades específicas para cada plataforma. Implementé server-side rendering (SSR) para optimizar la velocidad de carga y el SEO, logrando mejoras significativas en el rendimiento. Utilicé las mismas tecnologías que el proyecto principal (React, Next.js, TypeScript) pero con enfoque en crear experiencias únicas para cada plataforma. El desarrollo incluyó la integración con APIs existentes, implementación de Google Analytics, meta tags Open Graph para SEO, y optimización de posicionamiento en buscadores. Este proyecto demostró mi capacidad para trabajar de manera colaborativa y crear soluciones completas desde cero.",
    longDescriptionEn:
      "Developed from scratch, together with a colleague, two completely new news platforms: Kbeat and Spoiler. Although we based ourselves on the existing La República structure, we created both projects from start to finish, including new designs, complete layout and specific functionalities for each platform. Implemented server-side rendering (SSR) to optimize loading speed and SEO, achieving significant performance improvements. Used the same technologies as the main project (React, Next.js, TypeScript) but with focus on creating unique experiences for each platform. The development included integration with existing APIs, Google Analytics implementation, Open Graph meta tags for SEO, and search engine positioning optimization. This project demonstrated my ability to work collaboratively and create complete solutions from scratch.",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "SSR",
      "SASS",
      "Google Analytics",
      "SEO",
    ],
    achievements: [
      "Desarrollo desde cero de dos plataformas completas (Kbeat y Spoiler)",
      "Creación de diseños únicos y maquetación moderna para cada plataforma",
      "Implementación de SSR para optimizar velocidad de carga y SEO",
      "Integración eficiente con APIs existentes del Grupo La República",
      "Desarrollo colaborativo exitoso con un compañero",
      "Implementación de Google Analytics y meta tags Open Graph",
      "Optimización de posicionamiento en buscadores",
      "Creación de experiencias únicas para cada plataforma",
    ],
    achievementsEn: [
      "Development from scratch of two complete platforms (Kbeat and Spoiler)",
      "Creation of unique designs and modern layout for each platform",
      "SSR implementation to optimize loading speed and SEO",
      "Efficient integration with existing Grupo La República APIs",
      "Successful collaborative development with a colleague",
      "Google Analytics and Open Graph meta tags implementation",
      "Search engine positioning optimization",
      "Creation of unique experiences for each platform",
    ],
    category: "Frontend",
    year: "2022-2023",
    featured: true,
    images: [
      "/projects/kbeatspoiler/kbeatspoiler1.jpg",
      "/projects/kbeatspoiler/kbeatspoiler2.jpg",
      "/projects/kbeatspoiler/kbeatspoiler3.jpg",
      "/projects/kbeatspoiler/kbeatspoiler4.jpg",
      "/projects/kbeatspoiler/kbeatspoiler5.jpg",
      "/projects/kbeatspoiler/kbeatspoiler6.jpg",
      "/projects/kbeatspoiler/kbeatspoiler7.jpg",
      "/projects/kbeatspoiler/kbeatspoiler8.jpg",
      "/projects/kbeatspoiler/kbeatspoiler9.jpg",
    ],
  },
  {
    id: 9,
    title: "Garden Chic - E-commerce",
    titleEn: "Garden Chic - E-commerce",
    company: "Softaki",
    description:
      "E-commerce de plantas y servicios con login, carrito de compras y dashboard personalizado.",
    descriptionEn:
      "Plant and services e-commerce with login, shopping cart and custom dashboard.",
    longDescription:
      "Colaboré en el desarrollo frontend de este e-commerce especializado en venta de plantas y servicios, contribuyendo aproximadamente 60-70% del desarrollo frontend. Implementé el sistema de login completo con Next.js Auth, integración con Mercado Pago para la pasarela de pagos, carrito de compras funcional, y protección de rutas. El proyecto incluye animaciones fluidas y un diseño atractivo y moderno. Desarrollé un dashboard personalizado completo para la publicación de productos y blogs, con validaciones robustas usando Formik y Yup. El sistema cuenta con gestión de categorías, validación de productos, y un flujo completo de e-commerce desde el catálogo hasta el checkout. Trabajé en colaboración con otros compañeros desarrollando el proyecto desde cero hasta su finalización.",
    longDescriptionEn:
      "Collaborated in the frontend development of this e-commerce specialized in plant and service sales, contributing approximately 60-70% of frontend development. Implemented the complete login system with Next.js Auth, Mercado Pago integration for payment gateway, functional shopping cart, and route protection. The project includes fluid animations and an attractive, modern design. Developed a complete custom dashboard for product and blog publishing, with robust validations using Formik and Yup. The system includes category management, product validation, and a complete e-commerce flow from catalog to checkout. Worked in collaboration with other colleagues developing the project from scratch to completion.",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "TailwindCSS",
      "Next.js Auth",
      "Mercado Pago",
      "Formik",
      "Yup",
      "SEO",
    ],
    achievements: [
      "Colaboración en desarrollo frontend con 60-70% de contribución",
      "Implementación completa del sistema de login con Next.js Auth",
      "Integración exitosa con Mercado Pago para pasarela de pagos",
      "Desarrollo de carrito de compras funcional y protección de rutas",
      "Creación de dashboard personalizado para gestión de productos y blogs",
      "Implementación de validaciones robustas con Formik y Yup",
      "Diseño atractivo con animaciones fluidas y experiencia moderna",
      "Desarrollo colaborativo exitoso desde cero hasta finalización",
    ],
    achievementsEn: [
      "Frontend development collaboration with 60-70% contribution",
      "Complete login system implementation with Next.js Auth",
      "Successful Mercado Pago integration for payment gateway",
      "Functional shopping cart development and route protection",
      "Custom dashboard creation for product and blog management",
      "Robust validations implementation with Formik and Yup",
      "Attractive design with fluid animations and modern experience",
      "Successful collaborative development from scratch to completion",
    ],
    category: "Frontend",
    year: "2022",
    featured: true,
    liveUrl: "https://gardenchicperu.com",
    images: [
      "/projects/gardenchic/gardenchic1.png",
      "/projects/gardenchic/gardenchic2.png",
      "/projects/gardenchic/gardenchic3.png",
      "/projects/gardenchic/gardenchic4.png",
      "/projects/gardenchic/gardenchic5.png",
      "/projects/gardenchic/gardenchic6.png",
      "/projects/gardenchic/gardenchic7.png",
      "/projects/gardenchic/gardenchic8.png",
      "/projects/gardenchic/gardenchic9.png",
      "/projects/gardenchic/gardenchic10.png",
      "/projects/gardenchic/gardenchic11.png",
      "/projects/gardenchic/gardenchic12.png",
      "/projects/gardenchic/gardenchic13.png",
      "/projects/gardenchic/gardenchic14.png",
      "/projects/gardenchic/gardenchic15.png",
      "/projects/gardenchic/gardenchic16.png",
      "/projects/gardenchic/gardenchic17.png",
    ],
  },

  {
    id: 10,
    title: "UpTask - Administrador de Tareas",
    titleEn: "UpTask - Task Manager",
    company: "Proyecto Personal",
    description:
      "Aplicación full stack para gestión de tareas con colaboración en tiempo real y WebSockets.",
    descriptionEn:
      "Full stack application for task management with real-time collaboration and WebSockets.",
    longDescription:
      "Desarrollé una aplicación completa de administración de tareas full stack desde cero. El proyecto incluye un sistema robusto de gestión de tareas donde cada tarea puede tener colaboradores asignados que pueden ver el progreso y marcar tareas como completadas. Implementé WebSockets para comunicación en tiempo real, permitiendo que todos los colaboradores vean los cambios instantáneamente cuando alguien modifica una tarea. El frontend está construido con React, TypeScript y Redux para el manejo de estado, utilizando TailwindCSS para una maquetación moderna y responsiva. El backend utiliza Node.js con TypeScript y MongoDB como base de datos, proporcionando una API RESTful robusta. La aplicación cuenta con autenticación de usuarios, gestión de proyectos, asignación de colaboradores, y un sistema de notificaciones en tiempo real que mejora significativamente la experiencia de colaboración.",
    longDescriptionEn:
      "Developed a complete full stack task management application from scratch. The project includes a robust task management system where each task can have assigned collaborators who can view progress and mark tasks as completed. Implemented WebSockets for real-time communication, allowing all collaborators to see changes instantly when someone modifies a task. The frontend is built with React, TypeScript and Redux for state management, using TailwindCSS for modern and responsive layout. The backend uses Node.js with TypeScript and MongoDB as database, providing a robust RESTful API. The application includes user authentication, project management, collaborator assignment, and a real-time notification system that significantly improves the collaboration experience.",
    technologies: [
      "React",
      "TypeScript",
      "Redux",
      "Axios",
      "TailwindCSS",
      "Node.js",
      "MongoDB",
      "WebSockets",
      "REST API",
    ],
    achievements: [
      "Desarrollo full stack completo desde cero con React y Node.js",
      "Implementación de WebSockets para comunicación en tiempo real",
      "Sistema de colaboración donde múltiples usuarios pueden gestionar tareas",
      "Gestión de estado robusta con Redux en el frontend",
      "API RESTful con Node.js, TypeScript y MongoDB",
      "Interfaz moderna y responsiva con TailwindCSS",
      "Sistema de autenticación y gestión de usuarios",
      "Notificaciones en tiempo real para cambios en las tareas",
    ],
    achievementsEn: [
      "Complete full stack development from scratch with React and Node.js",
      "WebSockets implementation for real-time communication",
      "Collaboration system where multiple users can manage tasks",
      "Robust state management with Redux in frontend",
      "RESTful API with Node.js, TypeScript and MongoDB",
      "Modern and responsive interface with TailwindCSS",
      "Authentication system and user management",
      "Real-time notifications for task changes",
    ],
    category: "Full Stack",
    year: "2023",
    featured: true,
    liveUrl: "https://uptask-front.netlify.app",
    images: [
      "/projects/uptask/uptask1.png",
      "/projects/uptask/uptask2.png",
      "/projects/uptask/uptask3.png",
      "/projects/uptask/uptask4.png",
      "/projects/uptask/uptask5.png",
      "/projects/uptask/uptask6.png",
      "/projects/uptask/uptask7.png",
      "/projects/uptask/uptask8.png",
      "/projects/uptask/uptask9.png",
      "/projects/uptask/uptask10.png",
    ],
  },

  {
    id: 11,
    title: "Teslo Shop - E-commerce Full Stack",
    titleEn: "Teslo Shop - Full Stack E-commerce",
    company: "Proyecto Personal",
    description:
      "E-commerce completo con módulo de administración, carrito de compras e integración con PayPal.",
    descriptionEn:
      "Complete e-commerce with admin module, shopping cart and PayPal integration.",
    longDescription:
      "Desarrollé un e-commerce full stack completo desde cero como proyecto personal. El sistema incluye un módulo de administración robusto donde se pueden crear productos, visualizar todas las órdenes realizadas por los usuarios, gestionar usuarios registrados y acceder a un dashboard con estadísticas detalladas. El frontend cuenta con un carrito de compras funcional donde los clientes pueden seleccionar productos por categorías, navegar por el catálogo completo y realizar compras de manera intuitiva. Implementé integración completa con PayPal para procesamiento de pagos seguros. El sistema utiliza Next.js con TypeScript, Prisma como ORM, MongoDB como base de datos, y NextAuth para autenticación con proveedores como GitHub. Incluye protección de rutas, validaciones robustas con React Hook Form y Zod, y una interfaz moderna construida con TailwindCSS. El proyecto demuestra mi capacidad para desarrollar aplicaciones complejas con arquitectura full stack completa.",
    longDescriptionEn:
      "Developed a complete full stack e-commerce from scratch as a personal project. The system includes a robust admin module where products can be created, all orders placed by users can be viewed, registered users can be managed, and access to a dashboard with detailed statistics. The frontend features a functional shopping cart where customers can select products by categories, browse the complete catalog and make purchases intuitively. Implemented complete PayPal integration for secure payment processing. The system uses Next.js with TypeScript, Prisma as ORM, MongoDB as database, and NextAuth for authentication with providers like GitHub. Includes route protection, robust validations with React Hook Form and Zod, and a modern interface built with TailwindCSS. The project demonstrates my ability to develop complex applications with complete full stack architecture.",
    technologies: [
      "Next.js",
      "TypeScript",
      "Prisma",
      "MongoDB",
      "Node.js",
      "NextAuth",
      "PayPal",
      "React Hook Form",
      "Zod",
      "Axios",
      "TailwindCSS",
      "React Query",
      "React Table",
    ],
    achievements: [
      "Desarrollo full stack completo desde cero como proyecto personal",
      "Módulo de administración con gestión de productos, órdenes y usuarios",
      "Dashboard con estadísticas detalladas y métricas de ventas",
      "Carrito de compras funcional con selección por categorías",
      "Integración completa con PayPal para procesamiento de pagos",
      "Autenticación con NextAuth y proveedores como GitHub",
      "Protección de rutas y validaciones robustas con React Hook Form y Zod",
      "Interfaz moderna y responsiva con TailwindCSS",
    ],
    achievementsEn: [
      "Complete full stack development from scratch as personal project",
      "Admin module with product, order and user management",
      "Dashboard with detailed statistics and sales metrics",
      "Functional shopping cart with category selection",
      "Complete PayPal integration for payment processing",
      "Authentication with NextAuth and providers like GitHub",
      "Route protection and robust validations with React Hook Form and Zod",
      "Modern and responsive interface with TailwindCSS",
    ],
    category: "Full Stack",
    year: "2023",
    featured: true,
    liveUrl: "https://teslo-shop-rho.vercel.app",
    images: [
      "/projects/tesloshop/tesloshop1.png",
      "/projects/tesloshop/tesloshop2.png",
      "/projects/tesloshop/tesloshop3.png",
      "/projects/tesloshop/tesloshop4.png",
      "/projects/tesloshop/tesloshop5.png",
      "/projects/tesloshop/tesloshop6.png",
      "/projects/tesloshop/tesloshop7.png",
      "/projects/tesloshop/tesloshop8.png",
      "/projects/tesloshop/tesloshop9.png",
      "/projects/tesloshop/tesloshop10.png",
      "/projects/tesloshop/tesloshop11.png",
      "/projects/tesloshop/tesloshop12.png",
      "/projects/tesloshop/tesloshop13.png",
      "/projects/tesloshop/tesloshop14.png",
      "/projects/tesloshop/tesloshop15.png",
      "/projects/tesloshop/tesloshop16.png",
    ],
  },
];
