export const skillsData = {
  frontend: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "React Native",
    "Flutter",
    "Angular",
    "TailwindCSS",
    "SASS",
    "Redux",
    "Zustand",
    "React Query",
    "Material UI",
    "Ant Design",
    "Chakra UI",
    "Bootstrap",
  ],
  backend: [
    "Node.js",
    "Express",
    "NestJS",
    "MongoDB",
    "PostgreSQL",
    "TypeORM",
    "JWT",
    "GraphQL",
    "AWS",
    "Docker",
    "Web Sockets",
    "Redis",
  ],
  tools: [
    "Git",
    "GitHub",
    "Axios",
    "Vite",
    "SSR",
    "SEO",
    "React Hook Form",
    "Zod",
    "Next Auth",
  ],
};
